In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('nyc-taxi-zone-lookup.csv')

In [3]:
df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [9]:
df

,LocationID,Borough,Zone,service_zone
0,1,EWR,Newark Airport,EWR
1,2,Queens,Jamaica Bay,Boro Zone
2,3,Bronx,Allerton/Pelham Gardens,Boro Zone
3,4,Manhattan,Alphabet City,Yellow Zone
4,5,Staten Island,Arden Heights,Boro Zone
5,6,Staten Island,Arrochar/Fort Wadsworth,Boro Zone
6,7,Queens,Astoria,Boro Zone
7,8,Queens,Astoria Park,Boro Zone
8,9,Queens,Auburndale,Boro Zone
9,10,Queens,Baisley Park,Boro Zone
10,11,Brooklyn,Bath Beach,Boro Zone
11,12,Manhattan,Battery Park,Yellow Zone
12,13,Manhattan,Battery Park City,Yellow Zone
13,14,Brooklyn,Bay Ridge,Boro Zone
14,15,Queens,Bay Terrace/Fort Totten,Boro Zone
15,16,Queens,Bayside,Boro Zone
16,17,Brooklyn,Bedford,Boro Zone
17,18,Bronx,Bedford Park,Boro Zone
18,19,Queens,Bellerose,Boro Zone
19,20,Bronx,Belmont,Boro Zone
20,21,Brooklyn,Bensonhurst East,Boro Zone
21,22,Brooklyn,Bensonhurst West,Boro Zone
22,23,Staten Island,Bloomfield/Emerson Hill,Boro Zone
23,24,Manhattan,Bloomingdale,Yellow Zone
24,25,Brooklyn,Boerum Hill,Boro Zone
25,26,Brooklyn,Borough Park,Boro Zone
26,27,Queens,Breezy Point/Fort Tilden/Riis Beach,Boro Zone
27,28,Queens,Briarwood/Jamaica Hills,Boro Zone
28,29,Brooklyn,Brighton Beach,Boro Zone
29,30,Queens,Broad Channel,Boro Zone
...,...,...,...,...
235,236,Manhattan,Upper East Side North,Yellow Zone
236,237,Manhattan,Upper East Side South,Yellow Zone
237,238,Manhattan,Upper West Side North,Yellow Zone
238,239,Manhattan,Upper West Side South,Yellow Zone
239,240,Bronx,Van Cortlandt Park,Boro Zone
240,241,Bronx,Van Cortlandt Village,Boro Zone
241,242,Bronx,Van Nest/Morris Park,Boro Zone
242,243,Manhattan,Washington Heights North,Boro Zone
243,244,Manhattan,Washington Heights South,Boro Zone
244,245,Staten Island,West Brighton,Boro Zone
245,246,Manhattan,West Chelsea/Hudson Yards,Yellow Zone
246,247,Bronx,West Concourse,Boro Zone
247,248,Bronx,West Farms/Bronx River,Boro Zone
248,249,Manhattan,West Village,Yellow Zone
249,250,Bronx,Westchester Village/Unionport,Boro Zone
250,251,Staten Island,Westerleigh,Boro Zone
251,252,Queens,Whitestone,Boro Zone
252,253,Queens,Willets Point,Boro Zone
253,254,Bronx,Williamsbridge/Olinville,Boro Zone
254,255,Brooklyn,Williamsburg (North Side),Boro Zone
255,256,Brooklyn,Williamsburg (South Side),Boro Zone
256,257,Brooklyn,Windsor Terrace,Boro Zone
257,258,Queens,Woodhaven,Boro Zone
258,259,Bronx,Woodlawn/Wakefield,Boro Zone
259,260,Queens,Woodside,Boro Zone
260,261,Manhattan,World Trade Center,Yellow Zone
261,262,Manhattan,Yorkville East,Yellow Zone
262,263,Manhattan,Yorkville West,Yellow Zone
263,264,Unknown,NV,NaN
264,265,Unknown,NaN,NaN

In [13]:
df2 = pd.read_pickle('nyc-2017-yellow-taxi-trips-to-airport.pkl.gz')

In [19]:
df2.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2533072 entries, 0 to 2533071
Data columns (total 18 columns):
Unnamed: 0               int32
VendorID                 category
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count          int8
trip_distance            float16
RatecodeID               category
store_and_fwd_flag       category
PULocationID             int16
DOLocationID             int16
payment_type             category
fare_amount              float16
extra                    float16
mta_tax                  float16
tip_amount               float16
tolls_amount             float16
improvement_surcharge    float16
total_amount             float16
dtypes: category(4), datetime64[ns](2), float16(8), int16(2), int32(1), int8(1)
memory usage: 108.7 MB

In [16]:
df2.PULocationID = pd.to_numeric(df2.PULocationID, downcast='integer')

In [18]:
df2.DOLocationID = pd.to_numeric(df2.DOLocationID, downcast='integer')

In [39]:
df2.PULocationID.isin([263,264]).value_counts()

False    2471546
True       61526
Name: PULocationID, dtype: int64

In [41]:
df2.DOLocationID.isin([263,264]).value_counts()

False    2533072
Name: DOLocationID, dtype: int64

In [43]:
100*61526/2471546

2.4893730482863763

In [46]:
df.Zone.value_counts()[df.Zone.value_counts()>1]

Governor's Island/Ellis Island/Liberty Island    3
Corona                                           2
Name: Zone, dtype: int64

In [52]:
df.set_index('LocationID', inplace=True)

In [56]:
zones=df.Zone.to_dict()

In [63]:
df2.PULocationID.apply(lambda id: zones.get(id))

0                Greenwich Village North
1                        Lenox Hill West
2                           Central Park
3                       Garment District
4                            Murray Hill
5               Financial District South
6                  Upper West Side South
7                         Midtown Center
8               Financial District North
9                            Murray Hill
10                        Midtown Center
11                      Garment District
12                           Murray Hill
13                          Clinton East
14                         Midtown North
15             Times Sq/Theatre District
16                        Midtown Center
17                   Lincoln Square West
18                   UN/Turtle Bay South
19                           JFK Airport
20                        Yorkville West
21                   UN/Turtle Bay South
22                              Union Sq
23         Sutton Place/Turtle Bay North
24                    World Trade Center
25                        Midtown Center
26                          Midtown East
27                         Midtown South
28             Times Sq/Theatre District
29                      Garment District
                       ...
2533042              Lincoln Square East
2533043              Lincoln Square West
2533044        Times Sq/Theatre District
2533045        Times Sq/Theatre District
2533046                   Midtown Center
2533047               World Trade Center
2533048                     Midtown East
2533049        Times Sq/Theatre District
2533050            Upper East Side North
2533051         Financial District North
2533052                   Midtown Center
2533053                   Midtown Center
2533054                   Yorkville West
2533055                      JFK Airport
2533056                      JFK Airport
2533057         Financial District South
2533058        Times Sq/Theatre District
2533059                        Chinatown
2533060    Sutton Place/Turtle Bay North
2533061                    Midtown South
2533062                         Gramercy
2533063                      Murray Hill
2533064          Greenwich Village South
2533065                     Midtown East
2533066            Upper West Side South
2533067                LaGuardia Airport
2533068     Penn Station/Madison Sq West
2533069                    Midtown South
2533070                Battery Park City
2533071     Penn Station/Madison Sq West
Name: PULocationID, Length: 2533072, dtype: object

In [49]:
#df['pickup_zone'] = 
df2.PULocationID.apply(lambda id: df[df.LocationID == id].Zone)

KeyboardInterrupt:

In [48]:
df[df.LocationID == 138].Zone

137    LaGuardia Airport
Name: Zone, dtype: object